V7/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from blog.views import blog_list_view , blog_detail_view
from search.views import SearchView
from cart.views import cart_home
from .views import login_page, register_page, index , contact, thankyou , faq


urlpatterns = [
    path('admin/', admin.site.urls),
    # path("api/", include("V7_products.urls")),
    path('products/', include('V7_products.urls'), name='Products'),
    path("login/", login_page, name='Login'),
    path("register/", register_page, name='Register'),
    path('thankyou/', thankyou, name='Thankyou'),
    path('faq/', faq, name='FAQ'),
    path('', index, name='Index'),
    path('blog/', include('blog.urls'), name='Blogs'),
    path('contact/', contact, name='Contact'),
    path('cart/', include('cart.urls'), name='Cart'),
    path('search/', SearchView.as_view(), name='search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

V7_products/urls.py
from django.urls import path
from .views import product_list_view, ProductDetailSlugView

app_name = 'products' 

urlpatterns = [
	path("", product_list_view, name="list"),
	path("<str:slug>/", ProductDetailSlugView.as_view(), name='detail')
]

blog/urls.py
from django.urls import path
from .views import blog_list_view , PostDetailSlugView


app_name = "blog"

urlpatterns = [
	path("", blog_list_view, name="list"),
	path("<str:slug>", PostDetailSlugView.as_view(), name="detail"),
]

cart/urls.py
from django.conf.urls import url
from django.urls import include, path

from .views import cart_home, cart_update, checkout_home


app_name = 'cart'

urlpatterns = [
	path('', cart_home, name='home'),
	path('update/', cart_update, name='update'),
	path('checkout/', checkout_home, name='checkout')
]

V7/forms.py
# forms.py

from django import forms
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings

User = get_user_model()

class ContactForm(forms.Form):
	email = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
	message = forms.CharField(max_length=1024, widget=forms.Textarea(attrs={'class' : 'form-control'}))

class LoginForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
	password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={'class' : 'form-control'}))

class RegisterForm(forms.Form):
	username = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
	email = forms.CharField(widget=forms.TextInput(attrs={'class' : 'form-control'}))
	password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={'class' : 'form-control'}))
	confirm_password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={'class' : 'form-control'}))

	def clean_email(self):
		email = self.cleaned_data.get('email')
		qs = User.objects.filter(email=eamil)
		if qs.exist(widget=forms.TextInput(attrs={'class' : 'form-control'})):
			return forms.ValidationError('email exists in our system')
		return email

	def clean_username(self):
		username = self.cleaned_data.get('username')
		qs = User.objects.filter(username=username)
		if qs.exists():
			return forms.ValidationError("username exists select new one")
		return username

	def clean(self):
		data =  self.cleaned_data
		password = self.cleaned_data.get('password')
		confirm_password = self.cleaned_data.get('confirm_password')
		if password != confirm_password:
			raise forms.ValidationError('passwords must match')
		return data

V7/views.py
import json
import urllib

from django.http import HttpResponse
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate, login, get_user_model
from django.conf import settings


from .forms import LoginForm , RegisterForm , ContactForm

def index(request):
	context = {"title":"V7",} 
	return render(request,'index/index_template.html', context)


def thankyou(request):
	context = {"title":"thank you"}
	return render(request, 'contact/thankyou.html', context)

def contact(request):	
	if request.method == 'GET':
		form = ContactForm()
	else:
		form = ContactForm(request.POST or None)
		if form.is_valid():
			message = form.cleaned_data.get('message')
			email = form.cleaned_data.get('email')

			recaptcha_response = request.POST.get('g-recaptcha-response')
			url = 'https://www.google.com/recaptcha/api/siteverify'
			payload = {
				'secret': settings.RECAPTCHA_SECRET_KEY,
				'response':recaptcha_response
			}
		
			data = urllib.parse.urlencode(payload).encode()
			req = urllib.request.Request(url, data=data)

			response = urllib.request.urlopen(req)
			result = json.loads(response.read().decode())

			if result['success']:
				send_mail(
				'message from contact form', # subject
				 message,
				 email,
				 ['variantsvn@gmail.com'],
				)
				return redirect('/thankyou')
			else:
				messages.error('not valid')
				return redirect('/thankyou')
	context = {
		"title":"Contact",
		"form": form,
		"site_key": settings.RECAPTCHA_SITE_KEY
	} 

	return render(request, 'contact/contact.html', context)

def login_page(request):
	form = LoginForm(request.POST or None)
	context = {"form": form}
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(request,username=username, password=password)
		if user is not None:
			login(request,user)
			context['form'] = LoginForm()
			return redirect("index")
		else:
			print('err')
	return render(request,'auth/login_template.html', context)


def register_page(request):
	user = get_user_model()
	form = RegisterForm(request.POST or None)
	context = {"form": form}
	if form.is_valid():
		username = form.cleaned_data.get('username')
		password = form.cleaned_data.get('password')
		email = form.cleaned_data.get('email')
		confirm_password = form.cleaned_data.get('confirm_password')
		user.objects.create_user(username, email, password)  
		# authenticate email 
	return render(request,'auth/register_template.html', context)


def faq(request):
	context = {'':''}
	return render(request, 'faq.html', context)

V7/templates/base/base.html
{% load static %}
<!doctype html>
<html>
<head>
	<meta name="description" content="base template">
	<meta name="keywords" content="variant seven ecommerce esport">
	<link rel="shortcut icon" type="image/jpg" href="{% static 'images/favicon.png' %}"/>
	{% include 'base/css.html' %}
</head>
<body class="d-flex flex-column min-vh-100">
		{% include 'base/navbar.html' %}
		{% load django_bootstrap_breadcrumbs %}
		{% block breadcrumbs %}
		{% clear_breadcrumbs %}
		{% breadcrumb "Home" "Index" %}
		{% endblock %}
		{% render_breadcrumbs %}
			<div id="page-content">
				{% block content %}
				
				{% endblock %}	
			</div>
			{% include 'base/footer.html' %}
</body>
</html>

V7/templates/base/breadcrumbs.html
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
{% clear_breadcrumbs %}
{% breadcrumb "Home" "Index" %}
{% endblock %}

V7/templates/base/css.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

V7/templates/base/footer.html
{% load static %}
{% load fontawesome_5 %}
{% fontawesome_5_static %}
<div id="footer">
<footer class="section footer-classic context-dark bg-image">
        <div class="container">
        <div class="mx-auto">
          <div class="row row-30">
            <div class="col-md-4 col-xl-5">
              <div class="pr-xl-4">
                <h5>Pour Your Heart Out</h5>
                <!-- Rights-->
                <p class="rights"><span>©  </span><span class="copyright-year">2021</span><span> </span><span>Variant Seven</span><span>. </span><span>All Rights Reserved.</span></p>
              </div>
            </div>
            <div class="col-md-4">
              <h5>Contacts</h5>
              <dl class="contact-list">
                <dt>Address:</dt>
                <dd>your heart</dd>
              </dl>
              <dl class="contact-list">
                <dt>email:</dt>
                <dd><a href="mailto:#">variantsvn@gmail.com</a></dd>
              </dl>
            </div>
            <div class="col-md-4 col-xl-3">
              <h5>Links</h5>
              <ul class="nav-list">
                <li><a href="{% url 'FAQ' %}">tbd</a></li>
              </ul>
            </div>
          </div>
        </div>
		<div class="row">
				<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
					<ul class="list-unstyled list-inline social text-center">
						<li class="list-inline-item"><a href="https://twitter.com/VariantSeven" target="_blank">{% fa5_icon 'twitter' 'fab' %}</a></li>
						<li class="list-inline-item"><a href="https://www.instagram.com/variantseven/" target="_blank">{% fa5_icon 'instagram' 'fab' %}</a></li>
					</ul>
				</div>
				<hr>
			</div>
			</div>	
  </footer>
</div>

V7/templates/base/navbar.html
{% load static %}
{% load fontawesome_5 %}
{% fontawesome_5_static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Variant Seven</title>
  </head>

  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark justify-content-sm-start fixed-top"
    >
      <div class="container-fluid">
        <a class="navbar-brand order-1 order-lg-0 ml-lg-0 ml-2 mr-auto" 
          ><img id="NavLogo" src="{% static 'images/V7Logo.png' %}"/></a
        > 
        <button class="navbar-toggler align-self-start" type="button">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div
          class="collapse navbar-collapse p-3 p-lg-0 mt-5 mt-lg-0 d-flex flex-column flex-lg-row flex-xl-row justify-content-lg-end mobileMenu"
          id="navbarSupportedContent"
        >  
        {% include 'search/snippet/search-form.html' %}
          <ul class="navbar-nav align-self-stretch">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Index' %}">
                Home
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'products:list' %}">
                Product
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog:list' %}">
                Blog
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Contact' %}">
                Contact
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'Login' %}">
                Login
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'cart:home' %}">
                {{request.session.cart_items}} Cart
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="overlay"></div>
    <div class="container" style="padding:2rem !important;">
      <div class="row">

      </div>
    </div>
  </body>
</html>
</nav>
<style>
  .navbar {
    color: #7a1717;
  }

  .navbar-dark .navbar-brand {
    color: #7a1717;
  }
</style>
<script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.4.1/js/bootstrap.bundle.min.js"
      integrity="sha256-OUFW7hFO0/r5aEGTQOz9F/aXQOt+TwqI1Z4fbVvww04="
      crossorigin="anonymous"
    ></script>
<script>
$(document).ready(function() {
  var fixHeight = function() {
    $('.navbar-nav').css(
      'max-height',
      document.documentElement.clientHeight - 150
    );
  };
  fixHeight();
  $(window).resize(function() {
    //fixHeight();
  });
  $('.navbar .navbar-toggler').on('click', function() {
    fixHeight();
  });
  $('.navbar-toggler, .overlay').on('click', function() {
    $('.mobileMenu, .overlay').toggleClass('open');
  });
});
</script>